name: Compile & Run Smart Contract Unit Tests

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Setting Environment Variables
        run: echo Setting env variables - $INFURA_KEY $GAS_PRICE_GWEI_KEY $GAS_WEI_KEY $ADDRESS_COUNT_KEY $ADDRESS_COUNT_KEY $DEFAULT_ADDRESS_INDEX_KEY
        env:
          INFURA_KEY: my-infura-key-here
          GAS_PRICE_GWEI_KEY: 20
          GAS_WEI_KEY: 2500000
          MNEMONIC_KEY: my-mnemonic-value-here
          ADDRESS_COUNT_KEY: 5
          DEFAULT_ADDRESS_INDEX_KEY: 0
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.15.x'
      - name: Install Truffle Globally
        run: |
          yarn add global truffle@5.1.16
      - name: Install dependencies
        run: |
          yarn install
      - name: Compiling Smart Contracts
        run: |
          truffle compile
      - name: Executing Unit tests
        run: |
          yarn test
      - name: Executing Code Coverage Report
        run: |
          yarn test:coverage



